### ISSUE TITLE
Window grab mode isn't restored properly

### ISSUE THREAD

**Issue by TeamDman** [Plonq/bevy_rts_camera#20]
Setting the window grab mode to Confined a la

```rust

    app.add_plugins(DefaultPlugins.set(WindowPlugin {
        primary_window: Some(Window {
            cursor: Cursor {
                grab_mode: bevy::window::CursorGrabMode::Confined,
                ..default()
            },
            ..default()
        }),
        ..default()
    }));
```

storing it somewhere to be used during restoration instead of None should fix it

https://github.com/Plonq/bevy_rts_camera/blob/2136b0b7d8660c3b4964b6fc178d929b5f987cc0/src/controller.rs#L250
https://github.com/Plonq/bevy_rts_camera/blob/2136b0b7d8660c3b4964b6fc178d929b5f987cc0/src/controller.rs#L319

**Comment by Plonq** [comment]
Fixed in 0.7.1
