### ISSUE TITLE
Panics when minimising window

### ISSUE THREAD

**Issue by Joakker** [Plonq/bevy_rts_camera#21]
I'm on windows, and when minimising the game window while the rts camera is active, the game panics, complaining of a call to `Result::unwrap` on an `Err`:

![image](https://github.com/Plonq/bevy_rts_camera/assets/51842726/e99ce03f-e2fe-4066-95dc-6c478cb71d22)

**Comment by Plonq** [comment]
Thanks for the report. Fixed in 0.7.2
