### ISSUE TITLE
No way to reset camera smoothing

### ISSUE THREAD

**Issue by juliohq** [Plonq/bevy_rts_camera#23]
Sometimes you might want to reset the camera smoothing (e.g. either when you add the RTS camera to your app or to position it manually via code), but there doesn't seem to be a way to do that right now.

Commenting out the following line fixes the first issue though:
https://github.com/Plonq/bevy_rts_camera/blob/a3d6af349d758ba46df4886d9aa636386fe6f206/src/lib.rs#L189

The second issue is fixed by [my recent PR](https://github.com/Plonq/bevy_rts_camera/pull/22).

**Comment by Plonq** [comment]
I will remove that line to fix the initialization. I have responded in the PR for the second part.

**Comment by juliohq** [comment]
Closing as fixed in 9c7260f7f92394934b0279ec186e9c421bfb336e.
