### ISSUE TITLE
It seems that modifying the drag key in the control will result in an error

### ISSUE THREAD

**Issue by rendaoer** [Plonq/bevy_rts_camera#26]
<img width="421" alt="image" src="https://github.com/user-attachments/assets/65502ecc-f240-413b-834c-7f08d74f6a12">
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/2225cdc4-af76-4a5d-94d4-84999433b842">

**Comment by Plonq** [comment]
The line that is panicking is `logical_viewport_size().unwrap()`, and I cannot replicate it.

Can you please provide a minimal repro?

**Comment by rendaoer** [comment]
@Plonq 
[minimal repro](https://github.com/rendaoer/rtsc-test)
1. I used [bevy_lunex](https://github.com/bytestring-net/bevy_lunex) and [bevy_rts_camera](https://github.com/Plonq/bevy_rts_camera)
2. I created a title interface and clicked it to jump to the game interface, then an error message appeared, but no error message appeared if I directly entered the game interface. Maybe it's not your problem, but I can't find the problem.

**Comment by Plonq** [comment]
I can't seem to trigger the bug using your repro. Is there anything special you did?


https://github.com/user-attachments/assets/9b5812c8-df85-4275-b603-77c7e6072f76
